### ISSUE TITLE
是不是不支持3.0版本

### ISSUE THREAD

**Issue by superman02** [yuxiangping/mongodb-orm#3]
我本地mongodb是3.2.4，然后用你的框架，好像不行，总是报Connection failed because of authentication failure, please check you username and password.但是我用mongodbchef客户端是可以的

**Comment by yuxiangping** [comment]
这个框架当时 mongodb的最新版本是2.6的  所以是基于2.6的版本开发的 按道理说应该会向下兼容的  3.2的版本我看看有什么新变化 后续再更新上

如果你有时间的话可以看看这个类，欢迎commit
com.mongodb.client.MongoDataSource
