### ISSUE TITLE
是否支持像mybatis的if标签

### ISSUE THREAD

**Issue by superman02** [yuxiangping/mongodb-orm#4]
我需要动态定义条件查询，怎样使用的

**Comment by yuxiangping** [comment]
不支持if条件分支  建议分解查询条件  结合空值可被忽略的特性来实现

如：  if  v1 != null   列(column1 = v1)
         if  v1 == null  列(column2 = v1)

可直接写成 
<property column="column1 " name="v1" ignoreNull="true" />
<property column="column2" name="v1"  ignoreNull="true"/>

当v1==null  时  column2的查询条件会被忽略
